// src/styles/mapaScreen.styles.js
import { StyleSheet, Platform } from "react-native";
import { COLORS, RADIUS } from "../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background || "#F8FAFC",
  },
  mapContainer: {
    flex: 1,
    position: "relative",
    backgroundColor: "#F8FAFC",
  },
  iframe: {
    width: "100%",
    height: "100%",
    backgroundColor: "#F8FAFC",
    border: "none",
  },
  centerBox: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
  },
  loadingText: {
    marginTop: 8,
    fontSize: 12,
    color: COLORS.textMuted,
  },
  floatingCoordBox: {
    position: "absolute",
    top: 12,
    left: 12,
    right: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.primaryLight,
    padding: 10,
    elevation: 6,
    zIndex: 10,
  },
  coordRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  coordLabel: { fontSize: 10, fontWeight: "700", color: COLORS.textMuted },
  coordValue: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.textDark,
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
  },
  btnCrearCalle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#16A34A",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: RADIUS.sm,
  },
  btnCrearCalleText: { fontSize: 11, fontWeight: "800", color: "#FFFFFF" },
  floatingAccordionContainer: {
    position: "absolute",
    bottom: 12,
    left: 12,
    right: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    elevation: 8,
    overflow: "hidden",
    zIndex: 10,
  },
  accordionHeader: { flexDirection: "row", alignItems: "center", padding: 12 },
  headerCalle: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.textDark,
    textTransform: "uppercase",
  },
  headerTitulo: { fontSize: 13, fontWeight: "700", color: COLORS.textDark },
  accordionBody: {
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    backgroundColor: "#F8FAFC",
  },
  listItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 8,
    borderRadius: RADIUS.sm,
    marginBottom: 4,
    backgroundColor: "#FFFFFF",
  },
  listItemActive: { backgroundColor: "#EFF6FF" },
  listItemCalle: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.primary,
    textTransform: "uppercase",
  },
  listItemTitulo: { fontSize: 12, fontWeight: "600", color: COLORS.textDark },
  chipActivo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: COLORS.primary,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  chipActivoText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  cardActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: "#FFFFFF",
    gap: 8,
  },
  btnAppMaps: {
    flex: 1.2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    backgroundColor: "#0F172A",
    paddingVertical: 7,
    borderRadius: RADIUS.sm || 6,
  },
  btnAppMapsText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "800",
  },
  btnDetalleLista: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    backgroundColor: COLORS.primaryLight || "#DBEAFE",
    paddingVertical: 7,
    borderRadius: RADIUS.sm || 6,
  },
  btnDetalleListaText: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.primaryDark || "#1E40AF",
  },
});
